services:
  logger:
   build: ./logger
   environment:
     - LOGFL=uptime
     - DELAY=3
   volumes:
     - ./logs:/logs
   restart: on-failure
   depends_on:
     - web

  web:
   image: nginx:alpine
   ports:
     - "8080:80"
   volumes:
    - ./web:/usr/share/nginx/html:ro

