#!/usr/bin/env bash

count=0
counta=0

LOGFILE="/logs/${LOGFL}_$(date +'%Y-%m-%d_%H-%M-%S').log"

while [[ $count -lt 5 || $counta -lt 5 ]]; do
 echo "starts at $(date)" >> "$(pwd)/$LOGFILE"
 echo "$counta"
 echo "-----------------" >> "$(pwd)/$LOGFILE"
 df -h >> "$(pwd)/$LOGFILE"
 echo "-----------------" >> "$(pwd)/$LOGFILE"
 ((counta++))
 ((count++))
 sleep $DELAY
done
